### ISSUE TITLE
Breaking error when editing a disabled entry

### ISSUE THREAD

**Issue by juresrpcic** [wbrowar/craft-3-guide#1]
I have a multi-site setup and all entries (singles, channels, structures) report the same error when I disable them (this is the main disable, not "disable for site").

```Internal Server Error
Argument 1 passed to craft\services\Sections::getEntryTypesBySectionId()
must be of the type integer, null given, called in
C:\web\testwebsite\vendor\wbrowar\guide\src\services\GuideService.php on line 241
```

Really nice plugin otherwise, cheers!

**Comment by wbrowar** [comment]
Thanks, @juresrpcic! I'll have that fixed in the next release.
