### ISSUE TITLE
Can't convert template to editable user guide

### ISSUE THREAD

**Issue by stevehurst** [wbrowar/craft-3-guide#10]
Hi,

I get the following error when I try to convert guide templates into an editable user guide in the control panel

> The requested URL /admin/guide/new/_guide/assets was not found on this server.

I have an initial set of docs in my` templates/_guide` folder, and I want to convert them for editing within the control panel for my client,.

**Comment by wbrowar** [comment]
@stevehurst It looks like there's a bug in saving the converted template. I think I have an idea what's going on, so I'll try to get out a fix in a little bit.

**Comment by wbrowar** [comment]
@stevehurst in trying to recreate your issue I did a `composer clear-cache` and `composer install`, then I updated Craft to 3.0.24 using `Utilities > Updates` and I'm unable to get an error when converting a Twig template. Can you please try updating everything and see if that fixes it.

Also, are you getting that error when clicking `Save` on the Edit User Guide page, or is it happening when trying to go to the page after it's been converted?

Finally, to confirm that your page has saved, you should see an ID number appear on the same line as the page you just converted in the `Settings > Guide > Navigation` setting page. If you're not seeing this then it means the save didn't work. Is there an ID there?

**Comment by stevehurst** [comment]
@wbrowar I ran both Composer commands and I'm on Craft 3.0.24.

I have six guide pages created using templates. I want to convert them to editable guide pages using the `Convert to User Guide' button, and that is when I get the error. The link I see on that button is `.../admin/guide/new/_guide%2Findex`

If I look in Guide Settings, none of my template guide pages have IDs.

If I create a new guide page in the control panel, the line in settings does have an ID, but it also uses the Template Path of the last static guide before it.

**Comment by wbrowar** [comment]
Okay, I still don't know what the issue is, exactly, but I've figured out that it's happening on some servers and not on others.. I don't know when I'll have a fix in, but I'm working on it.

Thanks for your patience @stevehurst

**Comment by wbrowar** [comment]
@stevehurst I've figured out what the issue is and just pushed up version 1.3.2 that should fix it. Please let me know if that worked for you
