### ISSUE TITLE
3.1 compatible

### ISSUE THREAD

**Issue by jan-dh** [wbrowar/craft-3-guide#12]
I tried using the guide plugin, but whenever I pushed an update (and the project-config synced) all my guides were gone. Still in the database, but not shown in the CMS. 

I assume the plugin hasn't been made compatible with the new project-config setup?

**Comment by wbrowar** [comment]
Hi, Jan, yesterday I set up a new instance of Guide for a client on a 3.1 site and the template-based guides and adding and saving an existing guide into the database seems to be working alright, however, I've found a scenario that needs to be fixed for 3.1:

When you're creating a guide from the Guide CP section (using the `+ New Guide` button), it creates the guide, but tries to store the settings for the navigation into the Guide Settings part of the DB. This doesn't work when you have `allowAdminChanges` set to `false` (so you can use Project Config).

**Does this sound like the situation you're running into?**

If so, I was planning to fix that in Guide 2.0, but that won't be ready for a little bit. In the mean time, I'll create a migration to pull those navigation settings out of the plugin settings and into it's own table in the DB.

Please let me know if you're having other issues and I'll try to fix those too.

**Comment by jan-dh** [comment]
Hi, yes. That's exactly the issue I'm experiencing.

**Comment by wbrowar** [comment]
Jan, this should be all set in version `1.4.0`. The navigation is now set in the database via a new CP page. When you upgrade it'll run a migration that moves existing navigation items out of the plugin settings and into the new navigation.

Thanks for the heads up about this issue!
