### ISSUE TITLE
LICENSE doesn't seem to match project

### ISSUE THREAD

**Issue by khamer** [wbrowar/craft-3-guide#4]
Hey there - looking through the license, it mentions payment and other things that don't seem to be connected to this project, but other parts seem like standard MIT. Did you mean for this project to have a non-standard license?

**Comment by wbrowar** [comment]
Hi Kevin, this project is a commercial plugin for Craft CMS 3, so the license is the standard license written for commercial plugins by the Pixel & Tonic. Although, I did mistakingly have `MIT` written in the `composer.json` file (thanks for alerting me to that), I've made that change over to "proprietary".

Is there anything else that you've noticed that might indicate this as an `MIT` licensed project?

Also, just to add more confusion, I do have a separate project that _is_ licensed using the `MIT` license as this is an open source project to support this plugin: https://github.com/wbrowar/craft-guide-templates

**Comment by khamer** [comment]
I think the license itself looked like a typical open suorce license with some pieces editted in that mentioned things (like licenses) that wasn't mentioned at all in the README. I think the only thing I might do left is I might mention licensing or pricing somewhere in the README (or even proprietary) just to make it more clear. Thanks!

**Comment by wbrowar** [comment]
That sounds like a good idea! I'll update the README with pricing info to start. Thanks for the suggestion.
