### ISSUE TITLE
Static translations

### ISSUE THREAD

**Issue by wbrowar** [wbrowar/craft-3-guide#42]
- [x] Go through static labels and enable static translations in Twig.
- [x] Pass selected language into JS globals and pass statically translated labels in from Twig

**Comment by Djive** [comment]
Hey :)  9 months ago you told me you working on this translation thing.. and thats why Slideouts still not  relased

Just info in case you didnt see>> There is plugin https://plugins.craftcms.com/enupal-translate?craft4   that do all translations without changeing  any code in plugins..
