### ISSUE TITLE
Add ability to disable creating/editing guides from the CP

### ISSUE THREAD

**Issue by codyjames** [wbrowar/craft-3-guide#5]
I'd like to be able to disable creating/editing guides from the CP.

I'd also like to be able to disable the "Admin Log". Which would hide it from the sidebar and widget area.

**Comment by wbrowar** [comment]
Hey Cody, I'm planning on organizing the settings section for the next release, so I'll put in more control over the appearance of those sections. Thanks for the feedback!

**Comment by wbrowar** [comment]
This is all set in 1.3.0! I added toggles for all of the widgets and a kill switch for all user edited guides. This won't remove any widgets that are installed or delete any user guides, but you could remove those and then turn these features off if you'd like.

**Comment by codyjames** [comment]
Fantastic! Thanks so much!
