### ISSUE TITLE
[FR] Emoji support for markdown

### ISSUE THREAD

**Issue by KatieMFritz** [wbrowar/craft-3-guide#58]
Saving new Guides from the code editor errors out if you include any emojis. But emojis are very useful for documentation! 🎉

Error:
`General error: 1366 Incorrect string value: '\xF0\x9F\x98\x84\x0D\x0A...' for column 'content' at row 1`

**Comment by wbrowar** [comment]
Thanks for the suggestion, @KatieMFritz! I'm going to move this over to Discussions and share some good news there 😃
