### ISSUE TITLE
Unable to find the template “_layouts/sidebar” in "guide/index" at line 1.

### ISSUE THREAD

**Issue by codyjames** [wbrowar/craft-3-guide#6]
I updated to 1.3.0 and am getting this error. I have not edited anything.

**Comment by wbrowar** [comment]
Hmm. It looks like this is getting confused with a template file in Craft: `vendor/craftcms/cms/src/templates/guide/index`.

Could you please tell me what your Template Path setting is set to in Guide plugin settings?

**Comment by codyjames** [comment]
<img width="1232" alt="screen shot 2018-07-12 at 3 52 59 pm" src="https://user-images.githubusercontent.com/378665/42663733-ac13edb0-85eb-11e8-8815-877dbe95d5fa.png">

**Comment by wbrowar** [comment]
Hmm can you change it to `_guide/index` so it matches the first link in your nav? That might fix it for now, but i'll see if I can find a way to fix this, too.

**Comment by codyjames** [comment]
Tried that already. Did not work.

**Comment by wbrowar** [comment]
What's the URI of the page that you go to when clicking on the Guide CP link in the sidebar? it should be `admin/guide/home`? (unless you changed your `cpTrigger` to something other than `admin`

**Comment by codyjames** [comment]
Yup, it's `/admin/guide/home`

**Comment by wbrowar** [comment]
Hmm I get that error by going to `admin/guide/index`, but `admin/guide/home` seems fine when i match your settings.

**Comment by wbrowar** [comment]
I'll keep working on it and I'll see if i can recreate the problem. It might be something I can ask the P&T folks about since I don't know what `vendor/craftcms/cms/src/templates/guide/index` is all about.

**Comment by codyjames** [comment]
Looked into it a bit. Basically getting three errors. Maybe this is the main one: ```An exception has been thrown during the rendering of a template ("Class wbrowar\guide\assetbundles\indexcpsection\IndexCPSectionAsset does not exist").```

**Comment by codyjames** [comment]
I'm going to try to reinstall

**Comment by codyjames** [comment]
Wow, that was a pain in the butt. I think I just had some composer issues. Re-installing seemed to fix this.
