### ISSUE TITLE
Cannot include templates.

### ISSUE THREAD

**Issue by taylorcgaines** [wbrowar/craft-3-guide#7]
I cannot include any templates within another template when guide is rendering. Specifically happens when trying to add a guide to an entry.

**Comment by wsydney76** [comment]
A temporary workaround may be:

```
{% set oldMode = craft.app.view.getTemplateMode() %}
{{ craft.app.view.setTemplateMode('site') }}
{% include '_guide/custom/articlebody' %}
{{ craft.app.view.setTemplateMode(oldMode) }}
```

Not sure it works in all situations, and the use of a string instead of a constant (View::TEMPLATE_MODE_SITE) may break, but hey!

**Comment by wbrowar** [comment]
@taylorcgaines @wsydney76 I'm happy to let you both know that Guide 2 fixes the importing issue in both templates that you create via Twig and in guides that are created with the code edit.

I don't have an exact release date in mind, but it should be out sometime in July.

**Comment by KatieMFritz** [comment]
This isn't working for me currently, though it might be a syntax error? I'd love to be able to include components directly, without copying them, to make a living style guide a la Storybook. But I'm getting the following error when I try:


>  Unable to find the template “_site/components/test” in "guide_template_path/contentBlocks/actions.twig" at line 4. in guide with the slug: content-blocks-actions



File Setup:
```sh
templates
  _guides
    contentBlocks
      actions.twig
  _site
    components
      test.twig
```


actions.twig:
```twig
<h2>Actions</h2>

<h3>Button</h3>
{% include "_site/components/test" %}
```

test.twig:
```html
<div>
  <p>Hello world!</p>
</div>
```

**Comment by KatieMFritz** [comment]
The workaround above does work though.
