### ISSUE TITLE
Sections Subnav does not work.

### ISSUE THREAD

**Issue by taylorcgaines** [wbrowar/craft-3-guide#8]
Sections Subnav link entries do not function. The href populates on both the element and the link in the subnav, but it does not jump to the heading.

**Comment by taylorcgaines** [comment]
Whoops. Technical error. We were on an older version. Working now, thanks!

**Comment by wbrowar** [comment]
Okay! Glad to hear. It's moved a few times due to P&T making some adjustments to the main CP templates.
