### ISSUE TITLE
Emptying out the Nav in the Guide Settings throws this error.

### ISSUE THREAD

**Issue by taylorcgaines** [wbrowar/craft-3-guide#9]
![image](https://user-images.githubusercontent.com/27028426/43077887-601c50e4-8e4e-11e8-8ec2-e9f90604145a.png)

And it causes the user to be unable to access any of the CMS.

**Comment by wbrowar** [comment]
Ah okay, I'll do a sanity check there to make sure it's populated before looping through it. Thanks again for catching these things :)

**Comment by AndrewMac** [comment]
This one just bit me too ;-)
I think I'll leave it uninstalled for a while, and check back later on
Looking forward to a fix :-)

**Comment by wbrowar** [comment]
@taylorcgaines @AndrewMac Sorry this took so long to fix ... This should be fixed in [1f7bd3a](https://github.com/wbrowar/craft-3-guide/commit/a45d7bd9f816c88e8c17e039e7caee39b7b0f9e0#diff-4ac32a78649ca5bdd8e0ba38b7006a1e). If you're still seeing any errors like this, please let me know.
